# Generated by Django 6.0.4 on 2026-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationjob',
            name='adapters',
            field=models.CharField(blank=True, default='google_dork,whois_dns,github,contextual', help_text='Comma-separated adapter names', max_length=255),
        ),
    ]
