# Generated by Django 6.0.4 on 2026-04-18 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_app', '0002_investigationjob_adapters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigationjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Investigation Job', 'verbose_name_plural': 'Investigation Jobs'},
        ),
        migrations.AddField(
            model_name='investigationjob',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this investigation', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
