# Generated by Django 4.2.30 on 2026-04-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_app', '0003_alter_investigationjob_options_investigationjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationjob',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='unverified', help_text='Whether entity passed pre-verification checks', max_length=20),
        ),
    ]
