# Generated by Django 4.2.30 on 2026-04-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_app', '0004_investigationjob_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationjob',
            name='current_phase',
            field=models.CharField(blank=True, help_text='Current phase name for UI', max_length=100),
        ),
        migrations.AddField(
            model_name='investigationjob',
            name='progress',
            field=models.IntegerField(default=0, help_text='Investigation progress percentage (0-100)'),
        ),
    ]
