# Generated by Django 4.2.30 on 2026-04-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osint_app', '0005_investigationjob_current_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationjob',
            name='current_phase',
        ),
        migrations.RemoveField(
            model_name='investigationjob',
            name='progress',
        ),
    ]
